Keats/jsonwebtoken

benches/jwt.rs, examples/claims.rs, src/lib.rs
(sorry for the bundled commits, I can separate them into separate PRs if you need)
This looks pretty useful so I wanted to help improve the ergonomics a bit (and then got a bit sidetracked in making it faster). Most of the ownership was not required (so `to_owned` is generally unnecessary), as the majority of work cannot be done in-place (at least not with current libraries).
This commit fixes a potential timing attack on hmac verification: 486c4a87f9603250167e40d70da2845e04a07500
Performance change:
```bash
test bench_decode ... bench:      11,501 ns/iter (+/- 885)
test bench_encode ... bench:       5,036 ns/iter (+/- 511)
test bench_decode ... bench:       3,460 ns/iter (+/- 718)
test bench_encode ... bench:       3,964 ns/iter (+/- 516)
```
=> Improve user ergonomics, performance and deny a timing attack

src/errors.rs
Hi,
I am using your library for a project and was trying to implement error handling with my own custom error type and implementing From on your error and discovered that `jwt::errors::Error` doesn't implement `std::error::Error` so I decided to implement it. 
Let me know if this causes a problem.
=> Implemented std::error::Error for jwt::errors::Error

src/lib.rs
Fixes #9
I need `sign()` (and `verify()`) for an implementation of (a subset of) [ACME](https://ietf-wg-acme.github.io/acme/), so this exposes them.
=> Expose sign() and verify()

Cargo.toml, README.md, src/lib.rs, src/serialization.rs
This is PR updates serde to 1.0. The README and Cargo file have been updated to use 1.0. This will close out #27.
=> Update Serde to 1.0

Cargo.toml, src/crypto.rs
Before *ring* 0.9.3, it was possible to link multiple versions of *ring* into a program, e.g. if one version depended on *ring* 0.6 and another depended on *ring* 0.9. Unfortunately, this doesn't work, because the linker doesn't know to how to link *ring*'s C/asm code correctly in that kind of situation. *ring* 0.9.3 added a flag to its Cargo.toml to tell the Rust toolchain to stop allowing multiple versions of *ring* to be linked into the same program, to prevent any problems this may cause.
*ring* 0.9.4 was released with an update to make some crates easier to update to 0.9.x.
if you consider this a breaking change, let me know and I'll bump the version number to 3.0.0 instead of 2.0.1.
=> Update *ring* to 0.9.4.

.gitignore, src/lib.rs, src/serialization.rs
While upgrading from v1 to v2 of jsonwebtoken, the compiler was complaining that the `TokenData` struct was private, which indeed it it. It's marked `pub` within the `serialization` module, but that module isn't public itself.
I only made `TokenData` public, but could make the entire module public as well.
Happy to explain more or adjust as needed 😄
=> Make the `TokenData` struct public

README.md
Apparently jwt::decode expects the secret to be a slice. Thus blindly copying the example code from the readme gives a compilation error.
```
error[E0308]: mismatched types
--> src/service/auth.rs:43:35
|
43 |     jwt::decode::<Claims>(&token, "secret", &jwt::Validation::default())
|                                   ^^^^^^^^ expected slice, found str
|
= note: expected type `&[u8]`
found type `&'static str`
= help: here are some functions which might fulfill your needs:
- .as_bytes()
```
=> Fix jwt::decode documentation in readme

README.md
Hey @Keats ,
New to Rust so apologies if I missed  or overlooked anything obvious!
---
When trying to get started with your lib I got stuck on this compile time error:
After flailing for a bit I landed on a [serde GitHub issue that had a solution](https://github.com/serde-rs/serde/issues/856).
Notably:
> Adding serde to my dependencies fixes this.
---
So I went ahead and added `serde` to the example `Cargo.toml` in the README. Do let me know if there are any issues here!
=> Add `serde` dependency to example Cargo.toml

src/lib.rs, tests/lib.rs
Per #48, a new method should be added to decode a token without validating the signature. This is labelled as unsafe, since it definitely is. It solves my use case for `jwt-cli`, which the secret is generally not known.
- Solves #48
- `dangerous_unsafe_decode`
- No docs (aside from cargo) since people probably shouldn't use it
=> Add a method to decode a token without signature validation

src/crypto.rs
RS256/384/512 algorithm strings were mapped to HMAC-SHA256/384/512
enumerators.
=> Fix algorithm mapping.

README.md, src/crypto.rs, src/errors.rs, tests/lib.rs, tests/rsa.rs
As specified in https://tools.ietf.org/html/rfc7518#section-3.5
- PS256 - RSASSA-PSS using SHA-256 hash algorithm
- PS384 - RSASSA-PSS using SHA-384 hash algorithm
- PS512 - RSASSA-PSS using SHA-512 hash algorithm
Fixes #92 
This is a breaking change so it's a good chance to release with v7.
=> Support for RSASSA-PSS signing algorithm

examples/custom_chrono.rs
Using `chrono`'s `serde` feature uses ISO 8601 instead of a Unix 
timestamp as specified in RFC 7519 section 2, "NumericDate". This 
example uses  custom de/serialize functions as shown in the [serde.rs 
example, "Custom Date Format"](https://serde.rs/custom-date-format.html).
NOTE: Currently fractional values are not supported in the example, 
though they are in the spec.
Resolves #82
=> Add example of using `chrono::DateTime` in claims

CHANGELOG.md, src/validation.rs
- Validation.aud is now `Option<HashSet<String>>`
- audience validation tests for "any of these" membership
=> Updated aud within Validation, including membership validation testing

src/lib.rs, src/pem_encoder.rs, tests/ec/mod.rs, tests/rsa/mod.rs
It’s dirty and lacks documentation, tests probably can be relocated, but now a user of this library can make DER and PEMs of public key parameters
=> Add functions to create pems and ders of the public keys

src/errors.rs
Invoking `Error::to_string()` results in a stack overflow for various error types.  This is a simply fix to avoid the recursive call in `Display::fmt`.
=> Fix recursive Display::fmt implementation on Error to avoid stack overflow

src/decoding.rs, src/errors.rs
I ran into #120 as well, so did a little changes.
=> fix issue 120: DecodingKey can be converted to static

Cargo.toml, examples/custom_chrono.rs
Hi,
the provided example for custom `chrono` headers (https://github.com/Keats/jsonwebtoken/blob/master/examples/custom_chrono.rs) does not work, if the `chrono` timestamp contains milliseconds. I discovered this when implementing a test property for myself that ensured, encoding and decoding results in the identity.
One if my failures looked like this:
```
[src/auth.rs:131] cookie = DeviceCookie { 
sub: "\u{0}",                                                                    
nonce: "\u{0}",                       
exp: 2020-04-22T13:42:23.284112768Z,                                             
}                                    
[src/auth.rs:131] parsed = DeviceCookie {                                            
sub: "\u{0}", …
```
=> Fix Broken chrono Example

Cargo.toml
Base64:
https://github.com/marshallpierce/rust-base64/compare/v0.11.0...v0.12.1
The commits show that its mostly new stuff, modularization and the switch to no_std
=> Updating base64 to 0.12

src/algorithms.rs, src/header.rs
As discussed in #136, this will allow `Header` to be hashed. This also requires `Algorithm` to be hashable.
=> Derive Hash for Header and Algorithm

src/decoding.rs, src/lib.rs, tests/hmac.rs
As suggested in #130, renames `dangerous_unsafe_decode` to `dangerous_insecure_decode`. This is because "unsafe" has a very specific meaning in Rust, and this function is _not_ and `unsafe` function.
Note that this would be a breaking change and therefore require a major version bump.
=> Rename dangerous_unsafe_decode to dangerous_insecure_decode

src/decoding.rs, src/lib.rs, tests/hmac.rs
Discussed in #135.
Adds a new function `dangerous_insecure_decode_with_validation`, which is a middle-ground between `decode` and `dangerous_unsafe_decode`. It takes a `Validation` and uses the `validate` function to run validations, but it does not do any signature verification.
I added the same set of tests that `decode` and `dangerous_unsafe_decode` have:
1. Regular
2. Invalid token
3. Invalid signature
4. Invalid algorithm
The new function passes numbers 1 and 3, but fails for numbers 2 and 4.
Note: the tests appear to be failing due to compiling the latest version of `base64` (v0.12.2) on Rust 1.39.0.
=> Add dangerous_insecure_decode_with_validation

src/crypto/ecdsa.rs, src/crypto/mod.rs, src/crypto/rsa.rs
Re: https://github.com/Keats/jsonwebtoken/pull/148#issuecomment-689074489
This adds `sign_bytes` and `verify_bytes` functions in `crypto`, corresponding to the existing public `sign` and `verify` functions but accepting a message as bytes instead of as a string. The existing `sign` and `verify` functions are changed to be implemented in terms of the new `sign_bytes` and `verify_bytes` functions.
I changed the internal sign/verify functions to use bytes instead of strings rather than adding new functions there too, since those functions are not exported.
Signing and verifying messages as bytes instead of (base64url-encoded) strings is needed for the Unencoded Payload Option (#149).
=> Add sign and verify on bytes

src/decoding.rs, src/lib.rs
For #156. I'm essentially just pulling the signature verification steps into their own function that can be called independently, and then having `decode` call that new function rather than duplicating everything. I'm certainly not set on `verify_sig` as a function name, if you have suggestions.
=> add verify_sig fn

src/validation.rs
Hello,
We don't need to iterate over all possible hits in two sets by counting them, we just need the first hit to validate.
=> increasing performance over validation of audiences

README.md, src/decoding.rs, src/encoding.rs
Fixes #193.
Currently, the API docs for `EncodingKey` & `DecodingKey`, made no mention of the current key format limitations.
Also added instructions for EC key generation to the README.
=> Added EC docs to Encoding & Decoding key

src/errors.rs
The documentation for `ErrorKind::InvalidSubject` mentioned the `aud` claim instead of `sub`. This commit fixes it.
=> Docs: fix copy paste error in ErrorKind::InvalidSubject

benches/jwt.rs, src/decoding.rs, src/serialization.rs, src/validation.rs
The claims validation was done via deserializing into a Map, which
implies allocations/deallocations. This was done even if the map was not
used afterwards.
This commit improves performance of the validation by never
deserializing in a `Map`, and deserializing only when necessary, to
a struct that typically only borrows from the original b64-decoded
json string.
The validation function interface change required update to the tests,
which are also made easier to read by using the `serde_json::json!`
macro.
=> Improve deserialization performance around validation and its tests

src/validation.rs
In order to properly align with JWT NumericType wire protocol allow for type on wire to either be u64 or f64. In either case we convert in the most lossless way possible to a u64, so that nobody needs to know that the spec is overly permissive.
Fixes: #212
=> Numeric type

Cargo.toml, examples/custom_time.rs, tests/ecdsa/mod.rs, tests/eddsa/mod.rs, tests/hmac.rs, tests/rsa/mod.rs
Removes `chrono` as a dependency of the `next` branch. See #211.
=> (`next`) Remove chrono

src/errors.rs
=> Implement Clone, Eq and PartialEq for Error.

src/validation.rs
Default previously allocated 2 vecs now it's down to 1 without any noticeable change to the outer API or behaviour
=> Reduced default double allocation to one

src/validation.rs
=> Fix function name in doc comment

.github/workflows/ci.yml, src/header.rs, src/jwk.rs, src/validation.rs, tests/ecdsa/mod.rs, tests/eddsa/mod.rs, tests/hmac.rs, tests/rsa/mod.rs
Bumping the rustc version needed by dev dependency time 0.3.15 (derived from "0.3") that is now supporting rustc 1.59+.
=> fix ci: bump pinned rustc version to 1.59 (fixes #268)

src/decoding.rs, src/jwk.rs, tests/ecdsa/mod.rs, tests/eddsa/mod.rs, tests/rsa/mod.rs
- adding DecodingKey:from_ec_components DecodingKey:from_ed_components (equivalent of existing DecodingKey:from_rsa_components for ECDSA and EdDSA)
- adding tests
- adding DecodingKey:from_jwk
- adding tests for rsa, ecdsa and eddsa
=> Creating DecodingKey from jwk

src/errors.rs
`jsonwebtoken::Error` doesn't exist, needs to be `jsonwebtoken::errors::Error`
=> Fix comment on Result type alias

examples/auth0.rs, src/decoding.rs, src/errors.rs, src/jwk.rs
By using non-reference patterns to match references, the `ref` keyword becomes unnecessary as it is added by the desugaring.
=> style: use non-reference patterns instead of explicit ref in patterns

tests/ecdsa/mod.rs, tests/eddsa/mod.rs, tests/rsa/mod.rs
Suppress warnings like below:
https://github.com/Keats/jsonwebtoken/actions/runs/3997872968/jobs/6859764490#step:6:11
```
warning: unused imports: `Header`, `Validation`, `decode`, `encode`
Warning:  --> tests/ecdsa/mod.rs:3:5
|
3 |     decode, encode, Algorithm, DecodingKey, EncodingKey, Header, Validation,
|     ^^^^^^  ^^^^^^                                       ^^^^^^  ^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `time::OffsetDateTime`
Warning:  --> tests/ecdsa/mod.rs:6:5
|
6 | use time::OffsetDateTime;
|     ^^^^^^^^^^^^^^^^^^^^
```
=> Suppress warnings when `cargo test --no-default-features`

.github/workflows/ci.yml, Cargo.toml
`actions/checkout@v3` is available now: https://github.com/actions/checkout/blob/main/CHANGELOG.md
=> Update actions/checkout version

src/decoding.rs
If T: Clone, we can write a Clone implementation for `TokenData`.
=> Implement Clone for TokenData<T> if T: Clone

.github/workflows/ci.yml
Suppress these warnings: https://github.com/Keats/jsonwebtoken/actions/runs/4430067735
=> Update actions to avoid Node.js 12 actions

src/decoding.rs, tests/hmac.rs
DecodingKey::from_base64_secret uses standard decoding, while "k" field of a jwk is expected to be in base64url instead.
=> JWK hmac keys are base64url encoded not standard

Cargo.toml, src/pem/decoder.rs
- updating this removes the duplicate base64 dependency as pem 1.x used base64 0.13 still
=> Update pem dependency to 2.x

src/validation.rs
From the RFC:
> Each principal intended to process the JWT MUST
> identify itself with a value in the audience claim. If the principal
> processing the claim does not identify itself with a value in the
> "aud" claim when this claim is present, then the JWT MUST be
>rejected.
Closes #329
=> Reject tokens when claims has an aud, none expected

examples/auth0.rs, src/algorithms.rs, src/jwk.rs, src/lib.rs
Fix towards #252 
Added deserialization support for some missing algorithms in order to avoid panic while deserialization.
=> deserialization support for some missing algorithms

Cargo.toml, src/validation.rs
resolves #339 
I really don't like this approach though.
Why is setting the expiration time user controlled, but not validation? I have to import `chrono` so I can specify a timestamp for `exp`, but then the validation call is a black box that does something outside of user control. IMO, there shouldn't be a `get_current_timestamp` call. The user should have to supply one on calling `decode`, the same way they do when calling `encode`
=> Do what chrono does

src/validation.rs
Adding this allows us to continue using this library to decode a JWT token without a secret (the way it used to be possible pre v9).
Without this we cannot update to v9 and we are stuck in v8.3.
closes #335
=> Add the ability to decode a JWT token without specifying an audience.

.github/workflows/ci.yml, Cargo.toml, examples/custom_header.rs, examples/validation.rs, src/algorithms.rs, src/errors.rs, src/jwk.rs, src/validation.rs, tests/ecdsa/mod.rs, tests/eddsa/mod.rs, tests/header/mod.rs, tests/hmac.rs, tests/rsa/mod.rs
A few notes:
1) Wasm32 related tests cannot be run that easily, see https://github.com/rustwasm/team/issues/173. You have to use https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html and `wasm-pack`.
2) The `criterion` dev-dependency, only used for benchmarks, prohibits any compilation to the wasm32 target when using its default features (rayon in particular). This is now dependant on the targeted architecture.
3) Examples could not be compiled to wasm32, or any 32 bit target. The `Claims` struct from both `custom_hader.rs` and `validation.rs` had a `usize` field which got initialized with a value outside the u32 (usize on wasm32) range. Switching to an explicit u64 type in these structs seemed to be a reasonable fix?
4) Most crates provide some `wasm-...` feature, to …
=> Add wasm tests using was-bindgen-test and wasm-pack

examples/auth0.rs
The expected audience seems to be required as there is `aud` in the token.
=> Set expected audience to validation in auth0 example

examples/auth0.rs
Decouples auth0 examples' pattern matching to the more flattened structure, and uses header's `alg` for specifying the algorithm.
=> Refactor auth0 example

.github/workflows/ci.yml, Cargo.toml, src/validation.rs
This is a followup pull request, implementing the [simplified approach](https://github.com/Keats/jsonwebtoken/issues/365#issuecomment-1910186315) discussed on  https://github.com/Keats/jsonwebtoken/issues/365.
=> Add support for the reject_tokens_expiring_in_less_than option.

README.md, examples/validation.rs, src/validation.rs
Documentation is added in order to clarify the *required claims* for a token to be considered for validation. The `README` and the `Validation` struct have been modified.
The `examples/validation.rs` has been completed with an explicit call to `set_required_spec_claims`.
Resolves #376
=> Complete documentation with required claims

tests/rsa/README.md
Small fix to the docs here.
I was trying to use the same parameters this library uses for my own test keys and noticed there was a backtick here which stops an easy copy-paste.
=> docs: remove errenous backtick from rsa tests

Cargo.toml, README.md
According to https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md this does not affect this project. (Only change is a speedup, a minor change of the `InvalidLength` error, and a fixed `BIN_HEX`)
Also in a separate doc-only commit, address https://github.com/Keats/jsonwebtoken/pull/380#issuecomment-2030469801 to fix #380.
=>  Update base64 to 0.22 

src/jwk.rs
It is note set here:
https://login.windows.net/common/discovery/keys
=> fix: no panic if key_algorithm is not set in JWK

src/decoding.rs, src/encoding.rs
I've seen #220; however, as it mentions, `Debug` can be manually impl'd with sensitive fields redacted.
=> Implement Debug on Decoding/EncodingKey while redacting sensitive fields

src/algorithms.rs, src/decoding.rs, src/encoding.rs
A patch to hopefully fix all the AlgorithmFamily confusion. We ran into a very similar issue which i think are many describing here. But i noticed that _we_ specifically like to pin the validation of the jwt to the decoding/encoding key that is being used. But unfortunately this is currently not possible without adding more state tracking for our keys, which is annoying given that they already store this information. 
This patch will publicize a method to get the `AlgorithmFamily` from both encoding & decoding key. And also adds a method to AlgorithmFamily  that will return a list of all algorithms which are part of the family
=> Make family public

src/jwk.rs
This implements Hash for JwkSet, which allows it to be cached in a hashmap.
=> fix: implement hash for JwkSet

examples/auth0.rs
Uses `DecodingKey::from_jwk` to get `DecodingKey` from JWK in the auth0 example.
=> Use DecodingKey::from_jwk to get DecodingKey from JWK in auth0 example
